### ISSUE TITLE
Relatório de Movimentação do Caixa

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#103]
incluir nesse relatório o nome do cliente que fez o pagamento, pois, esta aparecendo apenas para os clientes que deixaram valor em aberto

**Comment by mtrystao** [comment]
[Inserir nome cliente relatorio.xlsx](https://github.com/jheizerwandel/webliniaerp-web/files/96026/Inserir.nome.cliente.relatorio.xlsx)

**Comment by filipecoelho** [comment]
Já foi solucionado em algum momento e não foi mapeado o desenvolvimento.
Estou finalizando.
