### ISSUE TITLE
Tela do PDV inserir botão para acessar a lista de produtos e preços

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#105]
Durante a venda preciso realizar uma consulta na lista de produtos, por esse motivo se faz necessário a inclusão de um botão para poder consultar a lista e depois voltar a tela de vendas sem perder a venda que esta em andamento

**Comment by filipecoelho** [comment]
Conforme informado pelo @mtrystao, não se faz mais necesário!
