### ISSUE TITLE
Nova Forma de Pgto - Promessa de Pagamento

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#107]
Precisamos inserir uma nova forma de recebimento que seria: Promessa de Pagto, para esse modelo de pagamento necessitamos dos seguintes campos:
Forma de Pgto:
Plano de Contas:
Conta:
Qtde de Parcelas:
Data:
Valor:
Nessa nova forma de pgto o valor so poderá ser debitado do saldo devedor do cliente apos ser confirmado o pgto do cliente

**Comment by jheizerwandel** [comment]
Arquivos Alterados WEB
      -> modified:   js/angular-controller/pdv-controller.js
      ->modified:   js/extras.js
      -> modified:   pdv.php
Arquivos Alterados API 
     ->modified:   controller/VendaController.php
     ->modified:   dao/UsuarioDao.php

**Comment by rafaelqw** [comment]
- Está finalizando uma venda com promessa de pagamento sem associar um cliente
- Está finalizando uma venda com promessa de pagamento sem associar um cliente com várias formas de pagamento junto

**Comment by jheizerwandel** [comment]
Arquivos Alterados WEB
modified:   js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Não está exibindo as formas de pagamento, por isso não consigo testar!

**Comment by rafaelqw** [comment]
Teste realizado tudo ok!
