### ISSUE TITLE
Importação de Danfe

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#12]
importar a danfe e atualizar automaticamente o estoque

**Comment by filipecoelho** [comment]
Foi implementado a funcionalidade que possibilita a leitura de XML de NF-e para obter informações dos produtos contidos na NF-e.
O algoritmo pesquisa cada produto na NF-e no banco de dados, através do campo de Código de Barras. Caso encontre, retornas as informações de cadastro deste produto, caso contrário, prevalece o critério da marcação do usuário, que escolhe entre cadastrar os produtos não encontrados ou marca-los na tela para que seja tratado manualmente.
As informações extraídas do XML são:
- Fornecedor
- No da NF-e
- Nome dos Produtos
- Valor de Custo
- % de Imposto
- Quantidades

**Comment by filipecoelho** [comment]
Os seguintes arquivos foram alterados:
----------------------------------------------------------------
webliniaerp-api
- config/func.php
- controller/EstoqueEntradaController.php
- dao/EstoqueEntradaDao.php
- dao/FornecedorDao.php
- dao/ItemPedidoFornecedorDao.php
- dao/ProdutoDao.php
- dao/RelatorioDao.php
- index.php
----------------------------------------------------------------
webliniaerp-web
- estoque.php
- js/angular-controller/estoque-controller.js
