### ISSUE TITLE
Relatorio de movimentação de estoque

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#13]
Opções de filtro:
- Filtro por tipo de movimentação

**Comment by jheizerwandel** [comment]
Arquivos Alterados API 
       modified:   config/func.php
        modified:   controller/EstoqueController.php
        modified:   controller/EstoqueSaidaController.php
        modified:   dao/EstoqueDao.php
        modified:   dao/EstoqueSaidaDao.php
        modified:   index.php
        modified:   model/EstoqueSaidaTO.php

**Comment by filipecoelho** [comment]
Layout desenvolvido e entregue no Git:
webliniaerp-web/rel-movimentacao-estoque.php

**Comment by jheizerwandel** [comment]
Atualizar Usuario caso esteja null

UPDATE tbl_estoque_saida AS tes
INNER JOIN tbl_vendas AS tv ON tes.id_venda = tv.id
	SET tes.id_usuario = tv.id_usuario
WHERE tes.id_usuario IS NULL

**Comment by rafaelqw** [comment]
- Incluir link no menu

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok

**Comment by rafaelqw** [comment]
- Não está informando o usuário de uma venda por Ordem de Produção

**Comment by rafaelqw** [comment]
Tudo ok!
