### ISSUE TITLE
Problema no cadastro interno de cliente

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#134]
- Ao editar o cadastro interno de cliente adicionando login e senha para o usuário, ao clicar em salvar o botão fica em "Aguarde..."
 - Erro no console: TypeError: Cannot read property 'nome' of null
    at Scope.ng.salvar (clientes-controller.js:329)
- Ao colocar o CNPJ, os dois últimos dígitos são alterados para 00

**Comment by rafaelqw** [comment]
Referente aos testes realizados no chamado #130

**Comment by jheizerwandel** [comment]
Arquivos Alterados
   ->controller/ClienteController.php

**Comment by rafaelqw** [comment]
Ponto 2 não resolvido e existe um chamado (#218) com mesmo problema

**Comment by jheizerwandel** [comment]
Arquivos Alterados API
->modified: config/func.php

**Comment by rafaelqw** [comment]
Teste realizado tudo ok!
