### ISSUE TITLE
Problemas na vitrine virtual

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#138]
- Os problemas identificados são:
 - Mesmo incluindo itens na grade da vitrine não são exibidos todos os produtos
 - Precisa separar a vitrine por empreendimento, no caso da Hage ao acessar a vitrine o cliente ve os produtos que estão em todas as lojas e não somente no deposito
 - Qdo o cliente estiver em uma pagina e clicar na foto e ao voltar deve permanecer na pagina em que ele estava navegando e não na pagina inicial
 - Não tem como pesquisar
- Ordenar produtos em ordem alfabética (primeiro Fabricante, depois Produto)
- Não está abrindo o link do arquivo nutricional
- A tela do carrinho não está funcionando

**Comment by rafaelqw** [comment]
Referente aos testes realizados no chamado #137

**Comment by rafaelqw** [comment]
Pontos 1, 2, 4,

**Comment by filipecoelho** [comment]
1.1 - São exibidos apenas os produtos que estão no estoque

**Comment by filipecoelho** [comment]
Alterar os arquivos:
- ```webliniaerp-web/carrinho.php```
- ```webliniaerp-web/vitrine.php```
- ```webliniaerp-web/detalhes.php```
- ```webliniaerp-web/js/angular-controller/vitrine-controller.js```
- ```webliniaerp-api/dao/GradeProdutosEcommerceDao.php```

**Comment by rafaelqw** [comment]
- Aparece o link para ver as informações nutricionais, mas não carrega a imagem
Resto tudo ok!
