### ISSUE TITLE
Problemas no PDV

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#140]
- Mensagem de produto não localizado ou sem estoque fica escondida quando o monitor é pequeno
- Ao ler um código de barras com o leitor e este for adicionado no carrinho deve voltar o foco para o campo de pesquisa por código de barra
- Está sendo possível fechar uma venda como orçamento sem associar um cliente
- Valor do desconto no comprovante de venda aparece sem formatação.
 - Exemplo: R$ 5 ou R$ 1.500750303267
- Na lista de pagamentos não está exibindo o nome da forma de pagamento
- Número da agência e da conta não devem ser obrigatórios para transf. bancaria e cheque
- Número do documento e número do boleto não devem ser obrigatórios no pgto em boleto
- No comprovante de venda não está exibindo o nome da forma de pagamento

**Comment by rafaelqw** [comment]
Referente aos testes realizados no chamado #139

**Comment by rafaelqw** [comment]
- Para fazer um orçamento não é necessário ter estoque
- Quando a forma de pagamento for Promessa de pagamento deve perguntar quando será pago
- Ao tentar fazer um pagamento com cheque, ainda está sendo obrigatório o número da conta

**Comment by filipecoelho** [comment]
Ponto 1 será tratado pelo chamado #163
Ponto 2 será tratado pelo chamado #164

**Comment by rafaelqw** [comment]
Ponto 3 não foi resolvido

**Comment by rafaelqw** [comment]
Problema resolvido
