### ISSUE TITLE
Problemas no Dashboard

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#146]
- Indicador Saldo Devedor aparece com valor negativo, quando os clientes somam saldo positivo em suas contas.

**Comment by mtrystao** [comment]
O indicador de saldo negativo de clientes no Dashboard continua com problemas, basta ver no empreendimento Lika Shoes o cliente Filipe possui um credito de R$ 1.008,00 mas o valor aparece como Saldo Devedor cliente

**Comment by jheizerwandel** [comment]
Arquivos alterados/criados WEB
    ->js/angular-controller/dashboard-controller.js

**Comment by rafaelqw** [comment]
O indicador de saldo negativo de clientes no Dashboard continua com problemas. No empreendimento Ambiente de Testes, apenas o cliente Denise Macedo aparece com saldo devedor de R$16,00 mas no Dashboard aparece R$316,00.

**Comment by jheizerwandel** [comment]
Realmente não estava trazendo o saldo devedor de alguns clientes,já resolvi, porem é importante lembrar que na listagem de clientes sempre são ocultos 3 usuários(222,498,1069), eles aparecem apenas para o empreendimento 6 , isso nos dois ambientes, então tem que tomar cuidado ao observar pela lista

**Comment by rafaelqw** [comment]
Problema testado e resolvido!
