### ISSUE TITLE
Transferencia de Mercadoria entre Deposito/Lojas

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#15]
para esse item deve ser considerado a realizacao de uma requisição por parte da loja que precisa do item e também gerar um relatório, pois, existe a necessidade de saber para qual loja deve ser lançado o custo do produto para pgto

**Comment by filipecoelho** [comment]
Ações disponíveis para administrador:
- Empreendimento solicitante emite uma requisição de transferência de mercadoria para um determinado empreendimento (escolhe qual) e emite um relatório de requisição de transferência;
- Empreendimento selecionado recebe uma alerta com a solicitação de transferência e ao clicar na alerta, é exibido a relação de produtos solicitados com as devidas quantidades;
-  Empreendimento selecionado pode manipular a requisição de transferência, incluindo e excluindo produtos e alterando quantidades.
- Empreendimento selecionado confirma o envio das mercadorias, que dá baixa no depósito selecionado e emite um relatório de transferência;
- Empreendimento solicitante recebe alerta de transferência realizada e ao chegar as mercadorias, confere com os relatórios emitidos e confirma o recebimento, que dá entrada no depósito que ele selecionar.
- Processo de transferência finalizado

**Comment by jheizerwandel** [comment]
Alteração DB

**Comment by jheizerwandel** [comment]
Foram alterados muitos aquivos que tem relação com entrada e saida de estoque , então sera necessário testar todos os processos que envolvem isso (ex:pdv)

**Comment by mtrystao** [comment]
Como vai funcionar todo esse processo?
Subiu para produção e não fizemos nenhum teste?
Em 13/04/2016 07:24, "jheizerwandel" <notifications@github.com> escreveu:
>
> Foram alterados muitos aquivos que tem relação com entrada e saida de
estoque , então sera necessário testar todos os processos que envolvem isso
(ex:pdv)

**Comment by mtrystao** [comment]
inserir coluna indicando a qtde de produtos de estoque disponível no Deposito selecionado, incluir na listagem de produtos solicitados e no MODAL de produtos

**Comment by filipecoelho** [comment]
Para solucionar o ponto 2:
- Comentar as linhas 69 e 79 ($("#top-nav").toggle();)
- Alterar a linha 68 para:
 - $("#main-container").css("margin-left", 0).css("padding-top", 45);

**Comment by mtrystao** [comment]
Os 02 itens que precisavam de ajustes foram realizados com sucesso!!!
Por favor, queira subir todas as alterações para o ambiente de produção da Hage
