### ISSUE TITLE
Implementar melhorias no mod de clinicas

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#165]
- Incluir chave de configuração para controle de tempo na fila de atendimento
- Incluir botão para informar profissional
- No modal de ficha do paciente, incluir aba de serviços executados, vinculando aos procedimentos "vendidos"
- Criar tela de controle de próteses

**Comment by jheizerwandel** [comment]
Campos para criar a tabela tbl_controle_protese
cod_paciente
cod_profissional_solicitante
cod_laboratorio (sera o codigo da tabela de  fornecedores))
dta_envio
dta_previsao_entrega
dta_entrega
cod_status (neste aqui serão apenas 3: Pendente de Envio, Em Produção e Entregue)

**Comment by jheizerwandel** [comment]
O item 3 do chamado não foi feito, ainda não definimos como vai funcionar, e também não entendi direito essa funcionalidade , preciso ver com  o @filipecoelho  para entender melhor

**Comment by filipecoelho** [comment]
@jheizerwandel vamos falar pelo hangout!

**Comment by rafaelqw** [comment]
Ponto 1 e 2 : Check-box  na tela de configuração foi criado, mas não consigo salvar a opção escolhida, por isso não aparece o botão.
Ponto 4: Tela criada, mas não tem link no menu. Os erros dessa tela são: não aparece os botões da coluna de Opção, e na lista de laboratório aparece os fornecedores.

**Comment by filipecoelho** [comment]
Ponto 1 e 2 OK;
Ponto 4 realmente não tem o link no menu.
Inclusive deve aparecer também o link da tela de cadastro de procedimentos.

**Comment by jheizerwandel** [comment]
Arquivos alterados/modificados API -  item 3
	->modificado:   controller/AtendimentoController.php
        ->modificado:   dao/AtendimentoDao.php
        ->modificado:   dao/EstoqueDao.php
        ->modificado:   dao/ItemVendaDao.php
        ->modificado:   index.php
        ->modificado:   model/ItemVendaTO.php

**Comment by jheizerwandel** [comment]
Arquivos alterados/modificados WEB - item 3

 	-> modificado:   controle-atendimento.php
        -> modificado:   js/angular-controller/controle_atendimento-controller.js
        -> modificado:   js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
Ponto 1 e 2 consigo salvar, mas quando tento cadastrar um novo atendimento para a fila de atendimento não salva e não exibe-o na lista, e com este problema não consigo verificar o ponto 2.

Ponto 4: Link adicionado, ao cadastrar um novo controle de prótese diz que ocorreu um erro ao salvar o controle

**Comment by rafaelqw** [comment]
- Incluir opção de escolher paciente na tela Controle de Atendimento
- Ocultar caixa de texto Agendamento do modal quando for selecionado algum cliente na opção da tela Controle de Atendimento 
- Quando a chave de configuração de Controlar tempo de atendimento for alterada para não, deverá ser ocultados as colunas de Inicio Atend., Fim Atend. na tela de Controle de Atendimento
- Horário de chegada está errado

**Comment by jheizerwandel** [comment]
Ponto 1 : feito 
Ponto 2 : não entendi bem , acho que quis dizer ocultar a possibilidade de acresentar um nono procedimento, o agendamento pode ser realizado sem problemas tenho otdas as informações para isso
Ponto 3 : isso já ocorre 
Ponto 4 : O horário da sua maquina pode estar errado, essa informação é enviada via JS , então o horário da maquina deve estar correto. Caso o problema não seja esse me chame no hangout para me mostrar o que esta ocorrendo, pq não identifiquei esse problema, com ressalva   do que relatei acima

**Comment by rafaelqw** [comment]
Ponto 2: O que eu quis dizer foi ocultar a possibilidade de Agendamento na aba Procedimento do modal da ficha do paciente
Ponto 3: O que está acontecendo é as informações não aparecerem mas as colunas devem ser ocultadas

**Comment by rafaelqw** [comment]
Problemas resolvidos!
