### ISSUE TITLE
Problema na listagem de procedimentos

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#166]
- A data está ficando com formatação errada

**Comment by jheizerwandel** [comment]
O problema não existe, fiz testes em produção e também em ambiente de teste e não ocorreu este problema

**Comment by rafaelqw** [comment]
Fui testar um procedimento no valor x, fiz um pagamento no valor x e não liberou o campo de data de agendamento na aba de Procedimento

**Comment by filipecoelho** [comment]
Conforme teste realizado em conjunto com @jheizerwandel, o problema não ocorreu.
