### ISSUE TITLE
Corrigir problema ao dar entrada em NF-e por XML

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#170]
- Apesar de salvar com sucesso, não está atualizando o valor de custo dos produtos;
- Na listagem do modal de produtos de um recebimento, não está listando/paginando todos os itens.

**Comment by jheizerwandel** [comment]
Alteração DB
UPDATE tbl_estoque_entrada AS tee 
INNER JOIN tbl_pedido_fornecedor AS tpf  ON tee.id_pedido_fornecedor = tpf.id
INNER JOIN tbl_fornecedores AS tf ON tpf.id_fornecedor = tf.id
	SET tee.id_fornecedor = tf.id

**Comment by rafaelqw** [comment]
Links http://www.hagesuplementos.com.br/webliniaerp-testes/clientes/estoque.php e http://www.hagesuplementos.com.br/webliniaerp-testes/hage/estoque.php não está listando os produtos da Nf-e e aparece o segundo erro no console na aba network: Parse error: syntax error, unexpected '[' in /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/controller/EstoqueEntradaController.php on line 39

**Comment by rafaelqw** [comment]
Ao salvar a NF-e dá o seguinte erro no console:

500 Internal Server Error

Unknown column 'id_usuario' in 'field list' (1)

#0 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/Conexao/Conexao.php(120): Conexao->execQuery()
#1 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/dao/EstoqueEntradaDao.php(18): Conexao->insert(Object(EstoqueEntradaTO))
#2 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/controller/EstoqueEntradaController.php(225): EstoqueEntradaDao->saveEstoqueEntrada(Object(EstoqueEntradaTO))
#3 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(189): EstoqueEntradaController::saveEstoqueEntrada()
#4 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Engine.php(303): flight\core\Dispatcher::execute(Array, Array)
#6 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->_start()
#7 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
#8 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#9 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Engine.php(63): flight\core\Dispatcher->run('start', Array)
#10 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->__call('start', Array)
#11 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->start()
#12 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Flight.php(43): flight\core\Dispatcher::invokeMethod(Array, Array)
#13 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/index.php(508): Flight::__callStatic('start', Array)
#14 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/index.php(508): Flight::start()
#15 {main}

**Comment by jheizerwandel** [comment]
Teste nos dois ambientes e não encontrei esse erro, salvou corretamente

**Comment by rafaelqw** [comment]
Os alinhamentos para a solução do problema foram definidos pelo Hangouts

**Comment by filipecoelho** [comment]
[nfe.xml.zip](https://github.com/filipecoelho/webliniaerp-web/files/243105/nfe.xml.zip)
Segue o arquivo xml que está sendo usado para os testes.

**Comment by jheizerwandel** [comment]
O problema não ocorre nem com o arquivo xml que esta no chamado

**Comment by rafaelqw** [comment]
500 Internal Server Error

Cannot add or update a child row: a foreign key constraint fails (`weblinia_teste_clientes`.`tbl_estoque_entrada`, CONSTRAINT `FK_tbl_estoque_entrada_tbl_usuarios` FOREIGN KEY (`id_usuario`) REFERENCES `tbl_usuarios` (`id`) ON DELETE CASCADE ON UPDATE NO ACT) (1)

0 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/Conexao/Conexao.php(126): Conexao->execQuery()
1 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/dao/EstoqueEntradaDao.php(18): Conexao->insert(Object(EstoqueEntradaTO))
2 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/controller/EstoqueEntradaController.php(225): EstoqueEntradaDao->saveEstoqueEntrada(Object(EstoqueEntradaTO))
3 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(189): EstoqueEntradaController::saveEstoqueEntrada()
4 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
5 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Engine.php(303): flight\core\Dispatcher::execute(Array, Array)
6 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->_start()
7 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
8 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
9 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Engine.php(63): flight\core\Dispatcher->run('start', Array)
10 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->__call('start', Array)
11 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->start()
12 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Flight.php(43): flight\core\Dispatcher::invokeMethod(Array, Array)
13 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/index.php(508): Flight::__callStatic('start', Array)
14 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/index.php(508): Flight::start()
15 {main}

**Comment by rafaelqw** [comment]
Não está atualizando o valor de tabela

**Comment by filipecoelho** [comment]
@rafaelqw já foi corrigido, porém precisa subir para produção.
@jheizerwandel fará isto
