### ISSUE TITLE
Remodelar layout de tela de pagamentos no PDV

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#171]
Criar botões com iconografia para facilitar a identificação e agilizar o preenchimento dos campos.
- MOCKUP DA TELA
 - ![captura de tela 2016-04-28 as 14 52 25](https://cloud.githubusercontent.com/assets/1401898/14895922/9eb37df8-0d51-11e6-95dd-1ffebda97b12.png)
- Código HTML de modelo do botão de cada forma de pagamento:
 - ``` <a data-loading-text=" Aguarde..." id="btn-logar" class="animation-delay5 bounceIn btn btn-default btn-sm" ng-click="logar()" style="max-width: 95px;word-wrap: break-word;white-space: inherit;padding-left: 5px;padding-right: 5px;"><i class="fa fa-3x fa-file-text-o" style="
    margin-bottom: 5px;
    margin-top: 5px;
"></i><span style="" class="clearfix">PROMESSA DE PAGAMENTO</span></a> ```
- Como é mostrado no mockup, ao selecionar uma forma de pagamento, na parte inferior será exibido os detalhes desta forma de pagamento, com seus devidos campos para preenchimento
- Um ponto importante é que para as formas de pagamento C. Débito e C. Crédito, se houver apenas uma maquina, já pré selecioná-la para facilitar a experiência do usuário.
- Incluir na aba de configurações do PDV do sistema, opções para informar quais formas de pagamento estarão disponíveis para o operador de caixa.

**Comment by filipecoelho** [comment]
''' <a data-loading-text=" Aguarde..." id="btn-logar" class="animation-delay5 bounceIn btn btn-default btn-sm" ng-click="logar()" style="max-width: 95px;word-wrap: break-word;white-space: inherit;padding-left: 5px;padding-right: 5px;"><i class="fa fa-3x fa-file-text-o" style="
    margin-bottom: 5px;
    margin-top: 5px;
"></i><span style="" class="clearfix">PROMESSA DE PAGAMENTO</span></a> '''

**Comment by filipecoelho** [comment]
Ajustes de layout dos botões realizado.
Seguir com o desenvolvimento.

**Comment by jheizerwandel** [comment]
Arquivos Alterados Web 
        -> modified:   js/angular-controller/pdv-controller.js
        ->modified:   pdv.php
