### ISSUE TITLE
Implementar forma de atualização de preços

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#172]
- Inserir nova aba Preços no cadastro de produtos
- Listar os empreendimentos associados ao produto
- Na listagem, exibir as 3 colunas de valores de venda:
 - Atacado
 - Varejo
 - Intermediário
- Nesta aba também será exibido o campo de valor de custo

**Comment by jheizerwandel** [comment]
Arquivos alterados API

       modified:   controller/ProdutoController.php
        modified:   dao/EstoqueDao.php
        modified:   dao/ItemVendaDao.php
        modified:   dao/PrecoProdutoDao.php
        modified:   dao/ProdutoDao.php
        modified:   index.php

**Comment by rafaelqw** [comment]
Aba Preço está presente apenas no link: http://www.hagesuplementos.com.br/webliniaerp-testes/clientes/produtos.php

**Comment by jheizerwandel** [comment]
O primeiro ponto sera resolvido no fim de semana .
O segundo ponto ocorreu pq o empreendimento não tinha chave de configuração id_produto_debito_anterior_cliente

**Comment by rafaelqw** [comment]
Ponto 2 resolvido!
