### ISSUE TITLE
Melhorias na tela de cadastro de fornecedores

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#175]
- Incluir campo de pesquisa no cadastro de fornecedores
- Incluir as colunas CNPJ/CPF, IE, Razão Social, Nome Fantasia na listagem
- Ordenar a lista em ordem alfabética (Nome Fantasia)
- Incluir dados bancários
- Incluir opção para cadastro de Pessoa Fisica
- Não permitir cadastrar duas vezes o mesmo fornecedor (usar o campo CNPJ/CPF como chave de validação)
- Incluir campo de complemento do endereço
- Incluir campos de telefone (Telefone 1, Telefone 2)
 - Ideal que se crie uma tabela de telefones (depois explico melhor)

**Comment by jheizerwandel** [comment]
* Ordenar pelo Nome Fantasia? não seria pela nome_fornecedor(Razão Social).
Os fornecedores que estão como pf não seriam ordenados , pois não tem nome fantasia

**Comment by jheizerwandel** [comment]
Alteração DB

ALTER TABLE .`tbl_fornecedores` 
ADD COLUMN `tipo_cadastro` SET('pf', 'pj') NULL DEFAULT NULL AFTER `id_empreendimento`,
ADD COLUMN `num_cpf` VARCHAR(50) NULL DEFAULT NULL AFTER `tipo_cadastro`,
ADD COLUMN `end_complemento` VARCHAR(255) NULL DEFAULT NULL AFTER `cod_cidade`,
ADD COLUMN `id_banco` INT(11) NULL DEFAULT NULL AFTER `end_complemento`,
ADD COLUMN `num_agencia` VARCHAR(50) NULL DEFAULT NULL AFTER `id_banco`,
ADD COLUMN `num_conta` VARCHAR(50) NULL DEFAULT NULL AFTER `num_agencia`


CREATE TABLE IF NOT EXISTS `weblinia_teste_clientes`.`tbl_telefone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tbl_referencia` VARCHAR(255) NOT NULL,
  `id_referencia` INT(11) NOT NULL,
  `num_telefone` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1

**Comment by jheizerwandel** [comment]
Arquivos Alterados/Criados WEB
->modified:   fornecedores.php
-> modified:   js/angular-controller/fornecedores-controller.js
->modified:   js/app.js

Arquivos Alterados/Criados API
 -> modified:   config/func.php
-> modified:   controller/FornecedorController.php
-> modified:   dao/FornecedorDao.php
-> new file:   dao/TelefoneDao.php
-> modified:   model/FornecedorTO.php
-> new file:   model/TelefoneTO.php
