### ISSUE TITLE
Melhorias nos lançamentos financeiros

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#176]
- Renomear o modal de fornecedores para o tal, hoje está falando em selecionar o  produto
- Na pesquisa de fornecedores, incluir outros campos de pesquisa:
 - CNPJ/CPF
 - Razão Social
 - Nome Fantasia
- Incluir as colunas na listagem de fornecedores
 - CNPJ/CPF
 - Razão Social
 - Nome Fantasia
- Ao confirmar o pagamento, deixar selecionar a conta a qual está vinculado o lançamento para que possa ser alterado
- Ao selecionar um cliente ou fornecedor e selecionar a forma de pagamento Transferência, preencher automaticamente os campos de dados bancários
- Trocar o combobox de Bancos para o Chosen ComboBox (c/ opção de pesquisa)
- Incluir opção para anexar documentos

**Comment by filipecoelho** [comment]
O ponto:
- Incluir opção para anexar documentos
Será incluso na nova versão de controle financeiro.

**Comment by jheizerwandel** [comment]
Arquivos Alterados Web
 ->modified:   controller/LancamentosFinanceirosController.php
 ->modified:   dao/FornecedorDao.php
 ->modified:   dao/PagamentoClienteDao.php
 ->modified:   dao/PagamentoFornecedorDao.php

Arquivos Alterados API
 ->modified:   js/angular-controller/clientes-controller.js
 ->modified:   js/angular-controller/lancamentos-controller.js
 ->modified:   lancamentos.php

**Comment by rafaelqw** [comment]
Itens relacionado ao fornecedor, não foram testados por causa do seguinte erro:
Fatal error: Class 'telefoneDao' not found in /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/dao/FornecedorDao.php on line 67
