### ISSUE TITLE
Melhorias nos pedidos personalizados

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#178]
- Incluir opção para selecionar modelo de estampa (produtos com o campo extra: flg_estampa)
- No relatório Controle Interno de Produção exibir foto do modelo da estampa (cadastrado no produto)
- Não ser obrigatório a seleção de cor de tira masculina para montagem da grade
- Incluir opção para tipo de base
 - Quadrado
 - Redondo
- Incluir opção para modelo de base
 - Linha Lika Shoes
 - Linha Personalizada
- Incluir na tabela de resumo, uma coluna com a quantidade total de pares
- No relatório Controle Interno de Produção, incluir campo informando o tipo de base (quadrado ou redondo) e o modelo de base (linha Lika Shoes ou linha Personalizada)
- No relatório Pedido de Venda (via Cliente), incluir campo informando o tipo de base (quadrado ou redondo) e o modelo de base (linha Lika Shoes ou linha Personalizada)
- No relatório Pedido de Venda (via Cliente), incluir coluna de total de pares na tabela de itens
- No relatório Pedido de Venda (via Cliente), incluir campo de observações do pedido
- Ao enviar o pedido para produção, fazer a validação de estoque

**Comment by filipecoelho** [comment]
Adicinado uma outra funcionalidade que não havia escrito acima:
- Opção na tela de configurações para ajustar tabelas de preços ;
- Chinelos quadrados, adicionar um valor por par (vide config. acima);
- Tamanhos maior que 41 adicionar um valor por par (vide config. acima).

**Comment by rafaelqw** [comment]
- Ao salvar um pedido, o mesmo não fica no topo da lista de pedidos
- Lista de pedidos está informando horário do pedido errado
- Ao ver detalhes de um pedido diz que a base escolhida é redonda sendo que foi escolhida quadrada
- Ao tentar incluir mais um item em um pedido, os dados que já estavam salvos do primeiro pedido são alterados pelo dados do segundo pedido
- Ao enviar um pedido para produção, os itens não são validados no estoque
- Ao tentar finalizar o processo de produção acontece o seguinte erro:

 - 500 Internal Server Error

Unknown column 'id_devolucao' in 'field list' (1)

0 /home/hagesuplementos/public_html/webliniaerp-                               testes/clientes/api/util/Conexao/Conexao.php(126): Conexao->execQuery()
1 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/dao/EstoqueEntradaDao.php(18): Conexao->insert(Object(EstoqueEntradaTO))
2 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/dao/PedidoVendaDao.php(124): EstoqueEntradaDao->saveEstoqueEntrada(Object(EstoqueEntradaTO))
3 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/controller/PedidoVendaController.php(656): PedidoVendaDao->finalizarPedido('58', Array)
4 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(189): PedidoVendaController::finalizarPedido()
5 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
6 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Engine.php(303): flight\core\Dispatcher::execute(Array, Array)
7 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->_start()
8 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(141): flight\core\Dispatcher::invokeMethod(Array, Array)
9 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
10 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Engine.php(63): flight\core\Dispatcher->run('start', Array)
11 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->__call('start', Array)
12 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/core/Dispatcher.php(188): flight\Engine->start()
13 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/flight/Flight.php(43): flight\core\Dispatcher::invokeMethod(Array, Array)
14 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/index.php(510): Flight::__callStatic('start', Array)
15 /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/index.php(510): Flight::start()
16 {main}

**Comment by jheizerwandel** [comment]
Ponto 8 : não existe a necessidade de por da mesma forma  do ponto 7, as informações já estão no nome do produto
