### ISSUE TITLE
Pré selecionar cliente após cadastro rápido

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#179]
Links http://www.hagesuplementos.com.br/webliniaerp-testes/clientes/pdv.php e http://www.hagesuplementos.com.br/webliniaerp-testes/hage/pdv.php

- Depois de salvar um novo cliente, o mesmo deve ficar seleciona no campo do cliente em que está sendo realizada a venda.

**Comment by jheizerwandel** [comment]
Arquivos Alterados WEB
->modified:   js/angular-controller/pdv-controller.js
->modified:   pdv.php

Arquivos Alterados API 
->modified:   controller/ClienteController.php

**Comment by rafaelqw** [comment]
Teste realizado tudo ok
