### ISSUE TITLE
Mapear telas para exportação p/ PDF

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#184]
Referente chamado #162

**Comment by rafaelqw** [comment]
- As telas que precisam ser exportadas para PDF ou CSV são essas
 - Rel. Analítico de Estoque
 - Rel. de Produtos Vencidos          
 - Rel. de Produtos a Vencer           
 - Rel. Total de Produto em Estoque    
 - Rel. c/ Estoque Mínimo              
 - Rel. de Vendas por Produto           
 - Rel. de Vendas por Produto por Mês 
 - Rel. de Vendas por Cliente
 - Rel. de Vendas por Vendedor
 - Rel. Fechamento Mensal
 - Rel. Pagamentos
 - Rel. de Contas a Pagar
 - Rel. Saldo Devedor de Cliente
 - Rel. de Contas a Receber
 - Rel. Resumo de Caixas
 - Rel. Movimentação de Caixas
 - Rel. Pagamentos Fornecedor
