### ISSUE TITLE
Inscrição Estadual IE

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#185]
O campo IE esta como campo obrigatório, contudo, empresa de Servicos na precisa possuir IE, dessa forma, esse campo não pode ser obrigatório

**Comment by filipecoelho** [comment]
Arquivos alterados API
modified: controller/ClienteController.php

Arquivos alterados WEB
modified: clientes.php

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok
