### ISSUE TITLE
Incluir campo de pesquisa na tela Devoluções

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#190]
Referente ao chamado #183

**Comment by rafaelqw** [comment]
Alterar os arquivos:

- ```webliniaerp-web/devolucao.php```
- ```webliniaerp-web/js/angular-controller/devolucao-controller.js```

- ```webliniaerp-api/dao/DevolucaoDao.php```
- ```webliniaerp-api/controller/DevolucaoController.php```

**Comment by mtrystao** [comment]
O campo esta criado e em produção, contudo, não esta funcionando
