### ISSUE TITLE
Incluir campo de pesquisa na tela Empreendimentos

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#196]
Referente ao chamado #183

**Comment by rafaelqw** [comment]
Alterar os arquivos:
- ```webliniaerp-web/empreendimento_config.php```
- ```webliniaerp-web/js/angular-controller/empreendimento_config-controller.js```

**Comment by mtrystao** [comment]
O campo esta criado e em produção, contudo, não esta funcionando
