### ISSUE TITLE
Alarme de Orçamento independente do período

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#208]
O alarme indicando que existe orçamento em aberto esta considerando os orçamentos em aberto no mês corrente é necessário que o alarme indique TODOS os orçamentos que estao em aberto independente do meu

**Comment by filipecoelho** [comment]
Arquivos alterados API
modified: dao/DashboardDao.php
modified: controller/DashboardController.php
modified: index.php

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok
