### ISSUE TITLE
Cadastro Cliente (Finalidade)

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#209]
Deve ser criado uma forma de poder criar e adicionar o campo Finalidade para os novos cadastros de acordo com o segmento do cliente, atualmente so existem opções referentes a suplementos

**Comment by filipecoelho** [comment]
Incluir botão de "mais" por enquanto.

**Comment by filipecoelho** [comment]
Em conversa com o Jheizer, alinhamos que iremos deixar o campo em aberto para que o usuário possa digitar os valores que deseja.
Assim não precisamos incluir uma tela de cadastro para este fim

**Comment by filipecoelho** [comment]
Atualizar os arquivos:
- ```webliniaerp-api/dao/ClienteDao.php```
- ```webliniaerp-api/dao/UsuarioDao.php```
- ```webliniaerp-api/controller/ClienteController.php```
- ```webliniaerp-web/clientes.php```

**Comment by rafaelqw** [comment]
Tudo ok!
