### ISSUE TITLE
Sea Cold Melhorias Modal comprovante de Venda e envio por E-mail

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#211]
Cliente Edvaldo esta solicitando para que o comprovante da venda realizada seja personalizada conforme o sistema que ele já utilizava e também para que seja possível enviar por e-mail

**Comment by mtrystao** [comment]
[ORÇAMENTOGAS PINHEIROS.13,04,2016-1.pdf](https://github.com/filipecoelho/webliniaerp-web/files/248977/ORCAMENTOGAS.PINHEIROS.13.04.2016-1.pdf)

Utilizar o modelo anexo para customizar o modal da venda para o empreendimento da Sea Cold cliente Edvaldo

**Comment by filipecoelho** [comment]
@mtrystao o comprovante solicitado tem todas as informações que o atual tem, porém em outro layout.
Acredito que seja possível negociar esse desenvolvimento, pois não tem nada de novidade neste modelo.

**Comment by filipecoelho** [comment]
Layout desenvolvido e entregue no Git
webliniaerp-api/util/rel_templates/comprovante_venda.php

**Comment by rafaelqw** [comment]
Acontece o seguinte erro:
![comprovante](https://cloud.githubusercontent.com/assets/6650717/16239582/c2f74002-37bb-11e6-8768-b17a5d4b499b.png)

**Comment by jheizerwandel** [comment]
Esqueci de subir os arquivos do relatório. Agora já estão no ambiente  de teste

**Comment by rafaelqw** [comment]
agora deu o seguinte erro: Fatal error: Class 'vendaDao' not found in /home/hagesuplementos/public_html/webliniaerp-testes/clientes/api/util/rel_templates/comprovante_venda.php on line 4

**Comment by filipecoelho** [comment]
Precisa incluir o campo saldo anterior na tabela e calculá-lo imediatamente antes de salvar a venda e colocar o botão de imprimir na tela de detalhes da venda, na listagem de vendas

**Comment by rafaelqw** [comment]
Quando eu insiro um email está aparecendo essa mensagem: Ocorreu um erro ao enviar o E-amail. E também tem que arrumar os erros de português da frase
