### ISSUE TITLE
Melhorias Transferencia de Mercadoria entre Deposito

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#212]
Identificamos a necessidade de realizar as seguintes melhorias.

0- O vendedor esta logado em um empreendimento e qdo vai fazer o pedido ele precisa indicar em qual deposito a mercadoria será inserida, mas como ele esta logado no empreendimento onde a mercadoria será dada entrada, acredito que esse processo pudesse ser automático Ex. Se logado no empreendimento da Hage 01 a mercadoria so poderá ser dada entrada no deposito da Hage 01, qdo houver mais de um deposito para o mesmo empreendimento devera aparecer a opção para escolher o deposito

1- Poder criar uma espécie de Orcamento do pedido de transferencia, pois, ao longo do dia o vendedor pode ir inserindo os produtos na lista

2- O Deposito deve possuir uma forma de realizar um pedido de transferencia para a loja diretamente sem a necessidade de aguardar o recebimento do pedido da loja (essa necessidade existirá quando chegar novos produtos no deposito, pq a loja não sabe da existência desses produtos)

3- É necessário clicar varias vezes ate chegar ao botão de TRANSFERENCIA deve ser criado um botão transferencia na primeira tela do sistema qdo se loga a fim de agilizar o processo, sugestão, inclua o botão TRANSFERENCIA em outra cor na linha onde aparece o nome do vendedor

4- Quando a loja for for realizar um pedido de transferencia devera ser apresentado somente os produtos que estão disponíveis no deposito para onde forem solicitar os produtos

5- Precisa ser alterado o Label do Campo de "Empreendimento" para "Selecione o Empreendimento onde será feito o Pedido

6- Organizar o layout de impressão na ordem que os produtos são lançados no sistema, pois, hoje a tela mostra uma ordem de produtos e na impressão aparece outra ordem

7- Inserir campo para pesquisa de transferencia

**Comment by filipecoelho** [comment]
Ponto 0: incluir chave de configuração para selecionar deposito padrao para o empreendimento e pré-selecionar; identificar que há somento 1 deposito para o empreendimento, pré-selecioná-lo
Ponta 1: incluir opção para editar e controle de status para enviar somente após confirmação
Ponta 2: solução adotada foi trocar de emp. e solicitar pelo tal
Ponto 3: Incluir botão na barra de cabeçalho (ao lado das alertas) e no menu suspenso de mais opções do PDV
Ponto 4: usando a chave de configuração do dep. padrão, mostrar apenas os produtos que tem estoque para aquele deposito (do empreendimento selecionado)
Ponto 5: trocar label

**Comment by filipecoelho** [comment]
Pontos 0 (em partes), 3, 5 e 7.
Faltando apenas os pontos: 1, 2, 4 e 6

**Comment by rafaelqw** [comment]
- Não está indentificando e pré-selecionando um único depósito
- Ao tentar adicionar um produto não aparece nenhum no modal

**Comment by jheizerwandel** [comment]
Ponto 0 -> O deposito sera pré-selecionado no momento em que a mercadoria for recebida, isso se o empreendimento tiver apenas um deposito, foi a forma solicitada no chamado, esta ocorrendo, inclusive testei no ambiente de teste

Ponto 1 -> Só vai aparecer se houver algum produto compartilhado entre ambos os empreendimentos e se estiver disponível em estoque no empreendimento  que ira ceder a mercadoria  , caso esse empreendimento estiver com o deposto padrão selecionado o sistema leva em consideração apenas esse deposito para cacular o disponibilidade  

Ponto 2 -> Descrito no ponto 1

Ponto 4 -> Descrito no ponto 1

**Comment by rafaelqw** [comment]
Ao solicitar uma transferência, está aparecendo o empreendimento em que estou e não deveria

**Comment by rafaelqw** [comment]
Ponto 1 não resolvido

**Comment by jheizerwandel** [comment]
Ponto 1 : O filipe disse que deve aparecer, tem clientes que querem realizar transferências entre depósitos do mesmo empreendimento
