### ISSUE TITLE
Implementar relatório de vendas por categoria

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#219]
Por solicitação do Saddam, da Baba Bidu, implementar relatório que retorne as vendas por categoria.

**Comment by filipecoelho** [comment]
Alterações do WEB:
	modified:   controle-atendimento.php
	modified:   controle_protese.php
	modified:   js/angular-controller/dashboard-controller.js
	new file:   js/angular-controller/rel-vendas-categoria_controller.js
	modified:   js/extras.js
	new file:   rel-vendas-categoria.php
	modified:   rel_vendas_produto.php

**Comment by filipecoelho** [comment]
@jheizerwandel favor atualizar os projetos do git na sua maquina local e subir para o ambiente de testes para que o @rafaelqw possa testar.

**Comment by filipecoelho** [comment]
@rafaelqw para testar basta selecionar algum período no Dashboard que exiba valores no gráfico de TOP 10 Vendas por Categoria e clicar em algum ponto do gráfico.

**Comment by rafaelqw** [comment]
Ao tentar realizar uma venda para seguir com os testes aconteceu o seguinte erro:
erro ao inserir venda

**Comment by rafaelqw** [comment]
Teste realizado
