### ISSUE TITLE
Problemas com selecionador de data

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#222]
Ao selecionar uma data no selecionador de datas, o mesmo não fecha. O erro acontece nas seguintes telas:
- Extrato
- Vendas por produto
- Vendas por produto por mês

**Comment by rafaelqw** [comment]
Chamado ainda não foi corrigido

**Comment by jheizerwandel** [comment]
no relatório  "vendas por produto por mês" o calendário não deve fechar mesmo, pq pode-se selecionar várias datas

**Comment by rafaelqw** [comment]
Tudo ok!
