### ISSUE TITLE
Problema na tela de Pedidos Personalizados

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#225]
Ao entrar na tela de Pedidos Personalizados aparece um etiqueta informando alguns erros. E ao clicar em novo pedido personalizado acontece o mesmo problema

**Comment by filipecoelho** [comment]
O problema acontece por tentar acessar a tela através de outro empreendimento.
Como a tela não é acessível através do menu em outro empreendimentos, vou desconsiderar por enquanto.
Quando o chamado #62 for implementado, esses problemas de ver telas sem permissão será resolvido.
