### ISSUE TITLE
Tratar Erro na tela de devolução

### ISSUE THREAD

**Issue by jheizerwandel** [filipecoelho/webliniaerp-web#231]
*Tratar erro na hora de salvar a devolução
*incluir id_devolução na tabela de entrada de estoque

**Comment by rafaelqw** [comment]
Acontece o seguinte problema na tela de Devolução
![problemas-devolucao](https://cloud.githubusercontent.com/assets/6650717/15297819/7d87ed4c-1b72-11e6-9eb5-732c3c8a4d47.png)

**Comment by filipecoelho** [comment]
@rafaelqw vou atualizar o ambiente de teste e depois você valida novamente, pois em desenvolvimento está funcionando normalmente.

**Comment by rafaelqw** [comment]
Teste realizado e problema resolvido!
