### ISSUE TITLE
Implementar Controle de Mesas e Comandas

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#243]
O fluxo já está mapeado, resta apenas implementá-lo.
O fluxo está em:
https://app.moqups.com/webliniaerp/7tp31gy3FB/view

**Comment by filipecoelho** [comment]
Layout dividido em duas partes, como mostram os anexos.
Referente a primeira parte está desenvolvido.
Os arquivos são:
controle-mesas.php
js/angular-controller/controle-mesas_controller.js
![captura de tela 2016-06-07 as 17 55 48](https://cloud.githubusercontent.com/assets/1401898/15893625/48a97e3c-2d57-11e6-9386-984bb1745b0f.png)
![captura de tela 2016-06-07 as 17 55 16](https://cloud.githubusercontent.com/assets/1401898/15893626/48ae4c78-2d57-11e6-83cb-a8e566532932.png)

**Comment by filipecoelho** [comment]
Segunda parte do layout desenvolvido e enviado  por e-mail!

**Comment by jheizerwandel** [comment]
Arquivos alterados WEB
       modified:   controle-mesas.php
        new file:   id_transferencia.php
        new file:   img/img-preload-app.jpg
        new file:   img/sem-imagem-app.png
        modified:   js/angular-controller/controle-mesas_controller.js
        modified:   js/angular-controller/pdv-controller.js
        modified:   js/app.js
        modified:   js/extras.js
        new file:   js/jquery.ease.js

**Comment by filipecoelho** [comment]
Segue o fluxograma do processo de emissão do cupom de ordem de produção:

**Comment by filipecoelho** [comment]
Pontos para corrigir:
- Ao abrir uma comanda, limpar a pesquisa do cliente (quando vou abrir outra comanda em qualquer outra mesa, o campo já está preenchido e deveria estar vazio)
- Ao adicionar um produto, limpar a pesquisa (quando vou adicionar outro produto, o campo já está preenchido e deveria estar vazio)
- Enviar a mensagem para impressora a partir da tela de Controle de Mesas (controle-mesas.php), pois a tela de Ordem de Produção (ordem_producao.php) pode estar aberta em varios computadores e enviar o comando varias vezes pra impressora.
- Ao finalizar uma venda, enviar uma mensagem pra tela de controle de mesas para atualizar a listagem (type: table_change)

**Comment by rafaelqw** [comment]
Ponto 1 não foi resolvido
Ponto 2 não foi resolvido
Pontos 3 e 4 ok

**Comment by rafaelqw** [comment]
Não aparece a imagem do produto quando estou selecionando quantidade.

**Comment by jheizerwandel** [comment]
* O layout que me foi passado não tinha foto nessa tela, apenas la listagem.
* Os pontos 1 e 2 estão ok, testei e funcionou de boa,  a não ser que esteja caindo em uma exceção muito especifica, lembrando que eu subi as alterações para o ambiente de teste

**Comment by rafaelqw** [comment]
- Ponto 1 conversei com o Filipe e ele pediu para incluir a imagem do produto nessa tela
- Ponto 2 só esta acontecendo quando adiciono outro produto e o problema foi detectado apenas no computador

**Comment by rafaelqw** [comment]
Ponto 3 ok

**Comment by jheizerwandel** [comment]
Ponto 1 sera feito depois

**Comment by rafaelqw** [comment]
Ponto 2 ok
