### ISSUE TITLE
Y de campo obrigatório não preenchido

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#247]
- Ao cadastrar um cliente e não preencher um campo obrigatório, deve aparecer uma mensagem informando que algum campo obrigatório não foi preenchido.

**Comment by jheizerwandel** [comment]
Arquivos Alterados  WEB
 ->modified:   clientes.php
 ->modified:   js/angular-controller/clientes-controller.js

Arquivos Alterados API
->modified:   controller/ClienteController.php

**Comment by rafaelqw** [comment]
Teste realizado
