### ISSUE TITLE
Problema no cálculo do custo de produtos em estoque

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#248]
- Não está sendo considerada a fórmula quantidade x valor de custo

**Comment by jheizerwandel** [comment]
Arquivos Alterados API
 ->modified:   controller/DashboardController.php
 ->modified:   dao/DashboardDao.php
 -> modified:   index.php

Arquivos Alterados WEB 
->modified:   js/angular-controller/dashboard-controller.js
