### ISSUE TITLE
Melhoria em orçamento

### ISSUE THREAD

**Issue by jheizerwandel** [filipecoelho/webliniaerp-web#249]
1- Perguntar ao usuário se ele deseja trabalhar com o valor de venda do momento em que o orçamento foi gerado ou com o valor atual.

**Comment by jheizerwandel** [comment]
Arquivos Alterados API
->modified: dao/ItemVendaDao.php
->modified: index.php

Arquivos Alterados WEB
->modified: js/angular-controller/pdv-controller.js

**Comment by rafaelqw** [comment]
- Ao tentar finalizar um orçamento e clicar em sim aparece uma janela informando o seguinte erro: o ID do orçamento é invalido

**Comment by jheizerwandel** [comment]
Alteração DB
DELIMITER $$
CREATE FUNCTION `calculaVlrOriginalItemVenda`(vlr_custo DOUBLE ,perc_margem_aplicada DOUBLE) RETURNS double
BEGIN
    RETURN  ROUND(vlr_custo + ( vlr_custo * perc_margem_aplicada ),2);
   END$$

DELIMITER ;
