### ISSUE TITLE
Incluir botão imprimir em algumas páginas

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#252]
- Incluir botão de imprimir nas seguintes páginas:
 - Relatório Contas a Pagar
 - Lançamentos Financeiros
 - Relatório Pagamentos a Fornecedores

**Comment by filipecoelho** [comment]
Arquivos alterados WEB
modified: rel_contas_pagar.php
modified: lancamentos.php
modified: rel_pagamentos_fornecedor.php

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok
