### ISSUE TITLE
Melhorias Detalhes da Venda e Relatório de Vendas por Cliente

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#253]
Fazer alteração na visualização dos comprovantes na tela de venda e no relatório de vendas por cliente, sugestão da alteração do relatório segue anexo

**Comment by mtrystao** [comment]
![relatorio de vendas](https://cloud.githubusercontent.com/assets/13888745/15724388/34e9ae7e-281d-11e6-8920-cc8817cd4d23.jpg)

**Comment by filipecoelho** [comment]
Foi atendido pelo chamado #211
