### ISSUE TITLE
Perfil de Caixa com acesso aos relatorios

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#256]
O perfil de caixa não pode ter acesso aos relatórios do empreendimento, favor, bloquear

Caixa possui acesso a:
Movimentacao de caixa (o usuario pode ver apenas o seu proprio relatorio)
Resumo de Caixa (bloquear)
Contas a receber (bloquear)
Contas a pagar (bloquear)
Fechamento mensal (bloquear)
Vendas por vendedor(o usuario pode ver apenas o seu proprio relatorio)
Vendas de produto mes a mes (bloquear)
Vendas p/ produto (bloquear)
Vendas por categoria (bloquear)
Estoque analitico (bloquear)

**Comment by jheizerwandel** [comment]
Arquivos Alterados WEB
->modified:   js/angular-controller/rel_caixas-controller.js
->modified:   js/angular-controller/relatorio-total-vendas-vendedor-controller.js
->modified:   rel-vendas-categoria.php
->modified:   rel_analitico_estoque.php
->modified:   rel_consolidado_caixa.php
->modified:   rel_contas_pagar.php
->modified:   rel_contas_receber.php
->modified:   rel_fechamento_mensal.php
->modified:   rel_total_vendas_vendedor.php
->modified:   rel_vendas_produto.php
->modified:   rel_vendas_produto_mes.php

**Comment by rafaelqw** [comment]
Tudo certo, mas será aberto um novo chamado para bloquear mais páginas e algumas funções
