### ISSUE TITLE
Dashboard - Indicadores com erro

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#258]
O indicador no Dashboard Custo total (Produtos em estoque)

**Comment by jheizerwandel** [comment]
Alteração DB
-> reescrever funções abaixo para :
DELIMITER $
CREATE FUNCTION `calcularCustoReal`(`vlr_custo` float, `perc_imposto_compra` float, `perc_desconto_compra` float)
	RETURNS float
BEGIN
    RETURN ROUND(( ifnull(vlr_custo,0) + (ifnull(vlr_custo,0) * ifnull(perc_imposto_compra,0) )) - ( ( ifnull(vlr_custo,2) + (ifnull(vlr_custo,0) * ifnull(perc_imposto_compra,0) )) * ifnull(perc_desconto_compra,0)   ) ,2);
END
$
DELIMITER $
CREATE DEFINER=`weblinia_erp`@`%` FUNCTION `calcularValorVenda`(`vlrCustoReal` float, `percLucro` float)
	RETURNS float
BEGIN
 RETURN  ROUND((vlrCustoReal + (vlrCustoReal * percLucro)),2);
END
$
