### ISSUE TITLE
Dashboard- Indicadores apresentando erro

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#263]
Os itens abaixo do Dashboard estao apresentando falha:
Custo total de produtos no Atacado,
 Custo total de produtos no Intermediário 
Custo total de produtos no Varejo
Cheques a compensar;
Cartão de Credito a Compensar;

**Comment by filipecoelho** [comment]
Tudo corrigido:
Alterar apenas a VIEW  vwl_pagamentos_venda:

```ALTER VIEW `vwl_pagamentos_venda`
AS SELECT
   `tpv`.`id_empreendimento` AS `id_empreendimento`,
   `tpv`.`data_pagamento` AS `data_pagamento`,
   `tpv`.`status_pagamento` AS `status_pagamento`,
   `tpv`.`id` AS `id_lancamento_entrada`,round(`tpv`.`valor_pagamento`,2) AS `valor_pagamento`,
   `tpv`.`id_forma_pagamento` AS `id_forma_pagamento`,
   `tpv`.`id_cliente` AS `id_cliente`,
   `tpv`.`id_maquineta` AS `id_maquineta`,
   `tpv`.`taxa_maquineta` AS `taxa_maquineta`,(case when ((`tpv`.`id_forma_pagamento` = 5) or (`tpv`.`id_forma_pagamento` = 6)) then round((`tpv`.`valor_pagamento` - (`tpv`.`valor_pagamento` * `tpv`.`taxa_maquineta`)),2) else round(`tpv`.`valor_pagamento`,2) end) AS `valor_real_recebimento`
FROM (((`tbl_pagamentos_venda` `tpv` join `tbl_conta_bancaria` `tcb` on((`tcb`.`id` = `tpv`.`id_conta_bancaria`))) left join `tbl_movimentacao_caixa` `mvc` on((`mvc`.`id_lancamento_entrada` = `tpv`.`id`))) left join `tbl_abertura_caixa` `tac` on((`tac`.`id` = `mvc`.`id_abertura_caixa`))) where ((`tcb`.`id_tipo_conta` <> 5) or ((`tcb`.`id_tipo_conta` = 5) and isnull(`tac`.`dta_fechamento`)));```

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok
