### ISSUE TITLE
Opção para configurar se quer manter o preço ou não

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#282]

**Comment by filipecoelho** [comment]
Alterar os arquivos:
- ```webliniaerp-web/empreendimento_config.php```
- ```webliniaerp-web/js/angular-controller/empreendimento_config-controller.js```
- ```webliniaerp-web/pdv.php```
- ```webliniaerp-web/js/angular-controller/pdv-controller.js```

**Comment by rafaelqw** [comment]
Tudo ok!
