### ISSUE TITLE
Opção para configurar se quer consolidar o valor total do estoque por empreendimento ou todos os depósitos compartilhados

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#286]

**Comment by filipecoelho** [comment]
- Primeiro: criar uma chave de configuração para o usuário (administrador) dizer se quais depósitos ele quer consolidar o custo total do estoque no painel de indicadores (Dashboard);
- Segundo: na aba de preços, do cadastro de produtos, exibir apenas os empreendimentos aos quais o usuário está associado. Com isso, bloqueia-se a possibilidade dele ver ou alterar informações pertinentes a outros empreendimentos dos quais ele não possui acesso.

**Comment by filipecoelho** [comment]
Solução consolidada: criar uma funcionalidade que permita ou não o usuário ver o custo total do estoque nas 3 telas:
- dashboard
- relatorio analitico do estoque
- relatorio de fechamento mensal

**Comment by jheizerwandel** [comment]
Não esquecer de subir: 
  -> util/login.php
  -> js/angular-service/user-service.js


INSERT INTO `tbl_funcionalidade` (`id`, `id_modulo`, `cod_funcionalidade`, `nme_funcionalidade`, `dsc_funcionalidade`) VALUES (13, 1, 'ver_estoque_todos_depositos', 'Ver Estoque de todos os depositos', 'Ver Estoque de todos os depositos');

INSERT INTO tbl_funcionalidade_perfil 
SELECT NULL,13,id FROM tbl_perfil_usuario
WHERE id_ref = 1 ;


INSERT INTO `tbl_funcionalidade` (`id`, `id_modulo`, `cod_funcionalidade`, `nme_funcionalidade`, `dsc_funcionalidade`) VALUES (14, 24, 'buscar_por_deposito', 'Fazer busca por deposito', 'Fazer busca por deposito');


INSERT INTO tbl_funcionalidade_perfil 
SELECT NULL,14,id FROM tbl_perfil_usuario
WHERE id_ref = 1 ;

INSERT INTO `tbl_funcionalidade` (`id_modulo`, `cod_funcionalidade`, `nme_funcionalidade`, `dsc_funcionalidade`) VALUES (34, 'buscar_venda_todos_depositos', 'Buscar Venda em todos os depositos', 'Buscar Venda em todos os depositos');

INSERT INTO tbl_funcionalidade_perfil 
SELECT NULL,15,id FROM tbl_perfil_usuario
WHERE id_ref = 1 ;

/*
	SELECT NULL,tbf.id,{$id_perfil} FROM tbl_funcionalidade AS tbf WHERE tbf.id NOT IN (13,14,15);
*/

**Comment by rafaelqw** [comment]
Ponto 2 não está mostrando a quantidade do depósito

**Comment by rafaelqw** [comment]
Tudo certo!

**Comment by filipecoelho** [comment]
Desativar o relatório analítico de estoque
