### ISSUE TITLE
Relatório de Categoria com problemas

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#291]
1- quando vc filtra por uma categoria e não inseri o período não publica as informações, deveria aparecer o acumulado de todo o período ou então uma msg informando que é necessário inserir o período de busca
2- insiro as informações de dt inicial e final e clico em filtrar as informações não são publicadas, deve publica o acumulado de todo o período ou então a msg de que deve ser inserido a categoria
3- nos campos de dt inicial e final so aparece o calendario quando vc clica na parte branca e nao no icone do calendario, deve existir um padrão
4- quando vc clica em imprimir abrem 02 janelas uma em branco e outra com a imagem do relatório
5- só é possível pesquisar uma categoria, deve constar o sinal de + para inserir mais categorias para realizar a pesquisa

**Comment by filipecoelho** [comment]
Está sendo atendido por conta do chamado #333

**Comment by rafaelqw** [comment]
Ainda só é possível pesquisar por uma categoria

**Comment by rafaelqw** [comment]
Tudo ok!
