### ISSUE TITLE
Desconto por perfil

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#30]
quando uma venda tiver o desconto maior do que o permitido para o perfil do vendedor devera aparecer uma tela solicitando a inserção de uma senha que possua desconto liberação de desconto superior a do usuário que estiver realizando a venda

**Comment by filipecoelho** [comment]
Já foi solucionado em algum momento e não foi mapeado e incluso na lista de tarefas do sprint
