### ISSUE TITLE
Filtrar produtos com estoque do deposito do caixa no pdv

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#308]
- Filtrar produtos com estoque do deposito do caixa no pdv, pois mostra o item zerado por conta da validade

**Comment by filipecoelho** [comment]
Não está corrigido!

**Comment by jheizerwandel** [comment]
O problema foi resolvido, mas quando fui testar no ambiente da Hage  estava demorando demais a carregar a listagem pela quantidade de dados ser bem maior que as dos clientes, vou tentar otimizara a query

**Comment by rafaelqw** [comment]
Tudo ok!
