### ISSUE TITLE
Cadastro de produtos otimizado

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#341]
- nome do produto, marca, quantidade e validade

**Comment by filipecoelho** [comment]
incluir módulo:
- ```nme_modulo```: Produtos
- ```tlt_modulo```: Produtos
- ```url_modulo```: produtos-optimized.php
- ```icn_modulo```: fa-archive
- ```id_modulo_pai```: 2
- ```psc_menu_modulo```: 1
- ```vsv_menu_modulo```: 1

**Comment by rafaelqw** [comment]
Não consigo escolher o depósito
