### ISSUE TITLE
Problemas no envio de mercadoria

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#342]
- Ao colocar uma certa quantidade pelo modal, as quantidades não aparecem na tela
- A quantidade exibida em estoque não bate com o que está cadastrado no produto

**Comment by filipecoelho** [comment]
Item 1 já foi tratado, precisa testar novamente.
Item 2 precisa ser retestado.

**Comment by rafaelqw** [comment]
Tudo ok!
