### ISSUE TITLE
Não excluir orçamentos, apenas marcar como excluido

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#348]
->Marcar orçamento como excluído e tirar de todos os relatórios,listagens  e indicadores   
->Criar tabela de log para guardar as informações pertinentes da ação

**Comment by jheizerwandel** [comment]
Dashboard	dashboard.php
Produtos	produtos.php
Vendas	vendas.php
Devoluções	devolucao.php
Dejesos	desejos_clientes.php
Extrato	extrato.php
Separar Venda	separar_venda.php
Controle de Estoque	estoque.php
Inventário de Estoque	inventario.php
Baixa Manual	baixa_estoque.php
Transferência	pedido_transferencia.php
Pedidos de Transferências	pedido_transferencia_recebido.php
Ordem de Produção	ordem_producao.php
Limpeza de Estoque	zera-estoque.php
Relatório Analítico de Estoque	rel_analitico_estoque.php
Relatório Analítico de Estoque	rel_produtos_vencidos.php
Relatório Analítico de Estoque	rel_produtos_vencer.php
Relatório Total Produto em Estoque	rel_total_produto_estoque.php
Relatório Analítico de Estoque	rel_produtos_estoque_minimo.php
Relatório de Vendas por Categoria	rel-vendas-categoria.php
Relatório de Vendas por Produto	rel_vendas_produto.php
Relatório de Vendas por Produto	rel_vendas_produto_mes.php
Relatório Consolidado de Vendas	rel_total_vendas_cliente.php
Relatório Analítico de Vendas	rel_vendas_cliente.php
Relatório de Vendas por Produto	rel_vendas_produto_mes.php
Relatório Consolidado de Vendas	rel_total_vendas_cliente.php
Relatório Consolidado de Vendas	rel_total_vendas_vendedor.php
Relatório de Fechamento Mensal	rel_fechamento_mensal.php
Movimentação de estoque	rel-movimentacao-estoque.php

**Comment by rafaelqw** [comment]
Tudo ok!
