### ISSUE TITLE
Relatório Produtos em Estoque

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#349]
Inserir no Relatório Produtos em Estoque uma coluna contendo o código de barras do produto

**Comment by filipecoelho** [comment]
Atualizar arquivos:
- ```webliniaerp-web/rel_total_produto_estoque.php```
- ```webliniaerp-web/js/angular-controller/relatorio-total-produto-estoque-controller.js```

**Comment by rafaelqw** [comment]
Tudo ok!
