### ISSUE TITLE
Comprovante de Venda

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#355]
Inserir no Comprovante de Endereco as informacoes de Numero do local e Bairro, essas informacoes constam no cadastro do cliente mas não aparecem no romaneio

**Comment by filipecoelho** [comment]
Atualizar arquivo:
- ```webliniaerp/api/util/rel_templates/comprovante_venda.php```

**Comment by rafaelqw** [comment]
Tudo ok!
