### ISSUE TITLE
Escolher tabela de preço para custo do produto no momento da transferência

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#358]
A idéia é que no momento da transferência o usuário possa selecionar qual a tabela de preço será considerada no custo do produto para o produto em questão, ou seja, ele pode selecionar uma tabela de preço para todos os produtos e individualmente pode selecionar outra tabela para cada produto.
O ponto é que ao efetuar a transferência, será alterado o custo do produto para o empreendimento que receberá este.

**Comment by rafaelqw** [comment]
Tudo ok!
