### ISSUE TITLE
Problema com solicitação e envio de mercadoria

### ISSUE THREAD

**Issue by rafaelqw** [filipecoelho/webliniaerp-web#375]
- Quando tento fazer um pedido de transferência diz que ocorreu um erro. Tela: pedido_transferencia.php
- Quando tento salvar e enviar um produto e clico no botão salvar e enviar, o botão salvar fica em aguarde. Tela: pedido_transferencia_recebido.php

**Comment by filipecoelho** [comment]
@rafaelqw Testar novamente e verificar se ainda ocorre os problemas

**Comment by rafaelqw** [comment]
Os problemas foram corrigidos
