### ISSUE TITLE
Compartilhar Categorias

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#6]

**Comment by filipecoelho** [comment]
Alterado a prioridade devido a relevância do problema

**Comment by filipecoelho** [comment]
Arquivos alterados:
- ```webliniaerp-web/categorias.php```
- ```webliniaerp-web/js/angular-controller/categorias-controller.js```
- ```webliniaerp-api/controller/CategoriaController.php```
- ```webliniaerp-api/dao/CategoriaDao.php```
