### ISSUE TITLE
inserir no cadastro rápido (PDV) os campos: data de nascimento e numero de telefone, deixar obrigatório ao menos um campo seja ele qual for                   Reprogramar obrigatoriedade de cadastro de cliente rápido

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#64]
- Incluir os campos data de nascimento e numero de telefone
- Nenhum dos campos são obrigatórios, exceto o perfil do cliente, que por padrão virá como Varejo.
- Cenário 1- O cliente pode ser cadastrado apenas pelo nome
- Cenário 2- O cliente pode ser cadastrado apenas pelo CPF

**Comment by jheizerwandel** [comment]
Arquivos alterados/criados API
        
         controller/ClienteController.php

**Comment by rafaelqw** [comment]
Melhoria realizada!
