### ISSUE TITLE
Incluir opção para desconto na venda inteira

### ISSUE THREAD

**Issue by filipecoelho** [filipecoelho/webliniaerp-web#68]
No PDV, incluir opção para dar desconto geral na venda

**Comment by jheizerwandel** [comment]
Arquivos alterados/criados WEB

	 modified:   js/angular-controller/pdv-controller.js
         modified:  pdv.php

**Comment by rafaelqw** [comment]
O desconto está se aplicando no último produto, e deve se aplicar ao valor da venda e não ao último produto

**Comment by rafaelqw** [comment]
Quando faço um desconto em real, o desconto se aplica em apenas no último produto e com isso faz o valor do produto ficar negativo

**Comment by jheizerwandel** [comment]
Coloque um exemplo , não consigo replicar o erro

**Comment by rafaelqw** [comment]
![desconto-valor-do-produto-negativo](https://cloud.githubusercontent.com/assets/6650717/15260142/860fa002-192b-11e6-8edd-0cd72d799d75.png)
