### ISSUE TITLE
Compartilhar Fabricantes

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#7]

**Comment by filipecoelho** [comment]
Alterado a prioridade devido a relevância do problema

**Comment by filipecoelho** [comment]
Arquivos modificados:
- ```webliniaerp-web/fabricantes.php```
- ```webliniaerp-web/js/angular-controller/depositos-controller.js```
- ```webliniaerp-web/js/angular-controller/fabricantes-controller.js```
- ```webliniaerp-api/controller/EmpreendimentoController.php```
- ```webliniaerp-api/controller/FabricanteController.php```
- ```webliniaerp-api/dao/EmpreendimentoDao.php```
- ```webliniaerp-api/dao/FabricanteDao.php```
- ```webliniaerp-api/index.php```
