### ISSUE TITLE
Compartilhar importadores

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#8]

**Comment by filipecoelho** [comment]
Alterado a prioridade devido a relevância do problema

**Comment by filipecoelho** [comment]
Arquivos alterados:
- ```webliniaerp-web/importadores.php```
- ```webliniaerp-web/js/angular-controller/importadores-controller.js```
- ```webliniaerp-api/controller/ImportadorController.php```
- ```webliniaerp-api/dao/ImportadorDao.php```

**Comment by mtrystao** [comment]
a lista de importador sumiu

**Comment by mtrystao** [comment]
a lista de fabricantes sumiu
