### ISSUE TITLE
Nao esta o funcionando os alertas para Novos Clientes e para Produtos que estão para vencer

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#89]
O Alerta para qdo um novo cadastro é criado não esta funcionando
Incluir na tela do cadastro a data em que o cadastro foi criado no sistema

**Comment by filipecoelho** [comment]
- Colocar chave de configuração que o usuário diga se quer ver a alerta de clientes sem login de acesso ao sistema

**Comment by filipecoelho** [comment]
Em relação aos produtos a vencer e vencidos já está pronto, o outro ponto será resolvido no chamado #

**Comment by rafaelqw** [comment]
Teste realizado, tudo ok
