### ISSUE TITLE
Opção para trocar de empreendimento

### ISSUE THREAD

**Issue by mtrystao** [filipecoelho/webliniaerp-web#9]

**Comment by rafaelqw** [comment]
- Em alguns relatórios está acontecendo de a pessoa clicar no botão mas não aparecer o modal de empreendimentos.
- Segue a lista:
 - rel_analitico_estoque.php
 - rel_produtos_vencidos.php
 - rel_produtos_vencer.php
 - rel_total_produto_estoque.php
 - rel_produtos_estoque_minimo.php
 - rel_vendas_produto.php
 - rel_vendas_produto_mes.php
 - rel_total_vendas_cliente.php
 - rel_total_vendas_vendedor.php
 - rel_fechamento_mensal.php
 - rel_contas_pagar.php
 - rel_saldo_devedor_cliente.php
 - rel_pagamentos_fornecedor.php

Não tem o botão: 
- rel_caixas.php

**Comment by filipecoelho** [comment]
@rafaelqw  fiz as correções, mas falta subir para o ambiente de testes..
@jheizerwandel  irá fazer isso.
